### ISSUE TITLE
review: align with tailwind

### ISSUE THREAD

**Issue by userquin** [antfu/unocss#124]
I have tested main entries from here https://tailwindcomponents.com/ except Dashboard and Account Card entries.

I will be adding rules here that are not on unocss preset, or that are misaligned with tailwind:
- [x] #125
- [x] #134
- [x] #128
- [x] #133
- [x] #130
- [x] #170
- [x] #132 
- [x] #180
- [x] #178
- [x] #136
- [x] #167

**Comment by userquin** [comment]
@antfu @hannoeru @edwardnyc

On weekend I'll do a second review.

**Comment by userquin** [comment]
Ofc Man, I added the task for it... you can also asign yourself the issue

**Comment by userquin** [comment]
@hannoeru  I assign it to you, see assignees from right panel on the issue, we need to check if the title can be changed or modify in some way, ot is huge

**Comment by xiaojieajie** [comment]
Hello, I want to help solve the seventh task（ object-center missing rule: object-position: center;, we should add the variants (top, right...)）

**Comment by hannoeru** [comment]
@xiaojieajie Click convert to issue button on right side of list to create issue and assign yourself, then you are good to go!

**Comment by xiaojieajie** [comment]
> @xiaojieajie单击列表右侧的转换为问题按钮以创建问题并分配给自己，然后就可以开始了！


Ask me, I created issue, but I don't think the task can be selected?

**Comment by chris-zhu** [comment]
Can i handle the last one?

**Comment by hannoeru** [comment]
@xiaojieajie Task will auto checked when you close that issue.

**Comment by hannoeru** [comment]
> Can i handle the last one?

Of course.

**Comment by userquin** [comment]
wtf: I created the issue this very morning, I just woke up and almost all the tasks started / closed, you are all amazing.

Thank you very much to all.

**Comment by UltraCakeBakery** [comment]
Can you add `translate-x-full`, `translate-y-full` and their negative variants to the list? @userquin

**Comment by SIGUSR97** [comment]
`::before` and `::after` variants do not have `content: ''` by default. This is misaligned with tailwind according to [this link](https://tailwindcss.com/docs/just-in-time-mode#pseudo-element-variants) and makes setting pseudo-elements practically ineffective. And there are no rules for `content-*` to set this content property. Another misalignment I found is space insertion/replacement when matching against [arbitrary values](https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support), rules like `h-[calc(1000px-4rem)]` will generate invalid CSS since spaces are not inserted in the correct places. Can we add support to these?

Also, I tried creating my own `content-*` rule as follows:
```ts
[/^content-\[(.*)\]$/, ([, content]) => ({ content })],
```
However, this is unable to match rules containing quotes such as `content-['']`. The regexp should be fine, did I miss out on something here?

**Comment by antfu** [comment]
> ::before and ::after variants do not have content: '' by default

I am not sure why TW does this, won't it affects overall client performance since now every element comes with two pseudo-elements.

> And there are no rules for content-* to set this content property

I am personally not a fan of this utility as I saw it kinda a mess to allow user provide arbitrary content in class, I feel that using inline style is more approach in this case.

> h-[calc(1000px-4rem)] will generate invalid CSS since spaces are not inserted in the correct places

That's a good point, added to the list.

> content-['']

Quotes are separators when we do the extracting. You can use JSON.strinify to escape the value:

```ts
[/^content-\[(.*)\]$/, ([, content]) => ({ content: JSON.stringify(content) })],
```

and use it like `content-[]`

**Comment by SIGUSR97** [comment]
First, thanks for your kind reply!

> I am not sure why TW does this, won't it affects overall client performance since now every element comes with two pseudo-elements.

If I remember correctly, `::before` and `::after` pseudo-elements won't render if no content property is provided. Which I think is why Tailwinds `content: ''` by default. 

> I am personally not a fan of this utility as I saw it kinda a mess to allow user provide arbitrary content in class, I feel that using inline style is more approach in this case.

And this is the one and only case where I find this `content-*` to be useful, that is used along with a `::before`/`::after` variant like so. (e.g. `before:content-['']`, `before:content-[counter(myCounter)]`)

> Quotes are separators when we do the extracting. You can use JSON.strinify to escape the value:

Hmm, not too big of a fan of having quotes as separators. I'm thinking if it's possible for user-defined custom separators as a field in our configuration? Something along the lines of `separators: [/\s/]`. Just a wild proposal.

**Comment by userquin** [comment]
epic
