### ISSUE TITLE
lit support 

### ISSUE THREAD

**Issue by bmalasani** [antfu/unocss#169]
Hi @antfu 

Does our unocss supports lit web components. I have tried using unocss with lit but unocss is unable to update the styles.

Please guide me how can we use unocss with lit.

thanks.

**Comment by userquin** [comment]
@antfu I can take a look at this, but we need to include another plugin to change the target custom element module, since we need to include the css from uno inside the css styles of the wc. `unocss` will just create the css, and so we need to transform the `import 'uno.css` to something like this `const __unoMyElement from 'uno.css'` (also include HMR here?) and then include the `css` (maybe force to use `scoped css`?):
```ts
import 'uno.css'

/**
 * An example element.
 *
 * @slot - This element has a slot
 * @csspart button - The button
 */
@customElement('my-element')
export class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
      border: solid 1px gray;
      padding: 16px;
      max-width: 800px;
    }
  `
  ...
}
```

**Comment by userquin** [comment]
I've a working example (I'm testing if there is a page reload), importing the css and including it inside component template with  `<style>${unocss}</style>` (the example is creating a `lit-ts` from vite `pnpm create vite => lit-ts`, see config bellow):

<details>
<summary><strong>src/my-element.ts</strong></summary>

```ts
import { html, css, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import unocss from 'uno.css'

/**
 * An example element.
 *
 * @slot - This element has a slot
 * @csspart button - The button
 */
@customElement('my-element')
export class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
      border: solid 1px gray;
      padding: 16px;
      max-width: 800px;
    }
  `

  /**
   * The name to say "Hello" to.
   */
  @property()
  name = 'World'

  /**
   * The number of times the button has been clicked.
   */
  @property({ type: Number })
  count = 0

  render() {
    return html`
      <style>${unocss}</style>
      <h1 class="mt-6em">Hello, ${this.name}!</h1>
      <button mt-6em @click=${this._onClick} part="button">
        Click Count: ${this.count}
      </button>
      <slot></slot>
    `
  }

  private _onClick() {
    this.count++
  }

  foo(): string {
    return 'foo'
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'my-element': MyElement
  }
}
```
</details>

<details>
<summary><strong>Vite Configuration</strong></summary>

```ts
import { defineConfig } from 'vite'
import UnoCss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    lib: {
      entry: 'src/my-element.ts',
      formats: ['es']
    },
    rollupOptions: {
      external: /^lit/
    }
  },
  plugins: [
    UnoCss({
      include: [/\.ts$/],
      presets: [
          presetAttributify(),
          presetUno()
      ],
      inspector: true
    })
  ]
})
```
</details>

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/143450378-e67c3650-70fd-4cef-9648-d1cca61bc26f.png)

**Comment by userquin** [comment]
I'm testing with this another approach on the wc, but seems to be not working, it should be the optimal solution (?):
```ts
<style>
@import 'uno.css';
</style>
```

**Comment by userquin** [comment]
Using `unsafeCSS` we can move the generated `uno css` to the `css` of the wc (in any case, page reload):

<details>
<summary><strong>src/my-element.ts</strong></summary>


```ts
import { html, css, LitElement, unsafeCSS } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import unocss from 'uno.css'

/**
 * An example element.
 *
 * @slot - This element has a slot
 * @csspart button - The button
 */
@customElement('my-element')
export class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
      border: solid 1px gray;
      padding: 16px;
      max-width: 800px;
    }
    ${unsafeCSS(unocss)}
  `

  /**
   * The name to say "Hello" to.
   */
  @property()
  name = 'World'

  /**
   * The number of times the button has been clicked.
   */
  @property({ type: Number })
  count = 0

  render() {
    return html`
      <h1 class="mt-6em">Hello, ${this.name}!</h1>
      <button mt-3em @click=${this._onClick} part="button">
        Click Count: ${this.count}
      </button>
      <slot></slot>
    `
  }

  private _onClick() {
    this.count++
  }

  foo(): string {
    return 'foo'
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'my-element': MyElement
  }
}
```
</details>

**Comment by userquin** [comment]
I uploaded 2 examples, previous code on `main` brnach and `per-module` in `permodule` branch on this repo: https://github.com/userquin/unocss-lit-ts

`mode: 'per-module'` is not working since the plugin will inject some code and will not return the css, and so the styles cannot be applied. Maybe we can include a flag for `lit` and do some extra transformations.

**Comment by userquin** [comment]
@antfu 

Playing with `per-module` https://imgur.com/IM0s58j, tmr I'll upload the changes, I need to fix the build, something broken on local.

We need to review this plugin since we need to allow also configure it with `enclosed` to be `pre`. For `lit` it should be `post` if using `pre` then we loose the `src`. I need to play with `vite + svelte` since `svelte plugin` will also transform the source and we need to include the `unocss plugin` before `svelte plugin` (/cc @dominikg): for `svelte, the solution would be similar to `vue-scoped`. Maybe we can split into 2 more plugins: `webcomponent/wc` and `svelte` (both scoped, former for shadow dom latter like `vue`).

I have 2 approachs, former using `@unocss-import` as comment, see `src/my-other-element.ts` at top, then the import with `.css` extension:

![imagen](https://user-images.githubusercontent.com/6311119/144691546-df9c8b06-8878-4b49-9c97-e42cc0a63175.png)

with generated code:

![imagen](https://user-images.githubusercontent.com/6311119/144691603-7d0846d4-f6cf-4c78-a707-9cb70f5d5a79.png)

latter using both in one, that is, the `virtual` entry and `@unocss-import` with `.css` extension:

![imagen](https://user-images.githubusercontent.com/6311119/144691490-9f322c8e-ef99-4c05-92b2-ee8ace6f8950.png)

with generated code:

![imagen](https://user-images.githubusercontent.com/6311119/144691613-3e0c4f09-570c-476a-acbf-eb84f904f7a7.png)
