### ISSUE TITLE
Discussion: what would it take to generate a set of Quasar presets to replace all of the predefined classes

### ISSUE THREAD

**Issue by julie777** [antfu/unocss#21]
I am putting this here because the project doesn't have a discussions area.
I am a quasar user and quasar provides many, many css classes. They also provide attributes that are similar. For me anyway this leads to trying to remember what goes where.

```
<q-btn label="press me" round flat class="q-pa-md q-ma-xs items-center float-left bg-red-1" />
```
(For the quasar users, I know that some of what I added doesn't apply to a button.)
From the example you can see that ```round``` and ```flat``` are attributes. On the  other hand ```items-center``` is a class.
For padding and margins there is a huge list of classes that use ```p[c]``` where c is the direction for the padding or margin and similarly the third group is sizing such as ```xs``` extra small or ```lg``` for large. 
Background colors provide another set of classes.

With my quick look at your documentation and the video @ldiebold just released. It seems like it would be pretty easy to provide an on-demand version of quasar css classes which could
- reduce the memory footprint by only providing what you use
- make everything usable as pseudo-attributes

In addition the [https://quasar.dev/style/spacing](Quasar doc) mentions that you can turn on breakpoint aware versions of CSS classes, but this will have a big impact on CSS footprint.

As a general aside, I am a huge fan of Quasar and Vue, and with SFCs and <script setup> and since I added unplugin-vue-components and unplugin-auto-import, my SFC files are simple and only contain important information. They are tiny.

**Comment by ldiebold** [comment]
Hi @julie777!
Some thoughts...

some of these attributes might be doing more than just changing css. Also, the css for "flat" on a button might be different to "flat" on a card, so they don't quite fit the atomic css paradigm. For that reason, they probably couldn't play nice with an atomic css framework.

As for the css classes, I've already brought this up with the team! I think it's a great idea, but would probably have to be implemented internally. For that reason (and since unocss is still experimental), we may have to wait some time before something like this could happen internally with Quasar. Also, Quasar includes its utility classes by default and to the best of my knowledge, this cannot be disabled (yet). I imagine that will likely change in the near future. However...

There's no reason we can't start using unocss with Quasar today! Quasar recently released a stable vite plugin and of course, unocss works with vite. We'll have to wait for unocss webpack support to get it working with other quasar projects.

I'll do a quick stream showing this setup and post it below :smiley:

**Comment by antfu** [comment]
> some of these attributes might be doing more than just changing css. Also, the css for "flat" on a button might be different to "flat" on a card, so they don't quite fit the atomic css paradigm. For that reason, they probably couldn't play nice with an atomic css framework.

This is also something we want to have on Windi v4, which I am still discussing its API interface with @voorjaar. Once the path becomes clear, we will implement the support to generate the class combinations in UnoCSS. Before that, you can also use the [full custom rule introduced in v0.3.0](https://github.com/antfu/unocss#full-controlled-rules) to generate multiple rules for the combinations (would be less on-demand, but should be fine if you don't expect too many of the combinations).

If the Quasar team has the interest to give UnoCSS a try, I am happy to collaborate and help!

Looking forward to that either way! 🙌

**Comment by ldiebold** [comment]
Oh wow, that's fantastic!

Just so I understand, imagine we have two components:
**Card**
```html
<q-card
  flat
/>
```

**Button**
```html
<q-btn
  flat
/>
```

Would unocss be able to apply different css to "button" than it does to "card"?
The reason I ask, is that "flat" can _mean something slightly different_ depending on the component.

We would need to be able to identify the component to make this possible. Also, edge cases like when the component is wrapped:
```html
<!-- BaseButton.vue -->
<template>
  <q-btn />
</template>
```

```vue
<base-button flat />
```

for this to work as expected, unocss would need to be able to:
- notice that `<base-button />` is wrapping a `q-btn`
- apply the `flat` css for a `btn` (as opposed to a `card`)

Not sure I'm explaining this well enough! Perhaps this use case is out of the scope of unocss, and actually belongs in "Quasar Land"... Or this would be possible using "full custom rule"?

**Comment by antfu** [comment]
Oh, yeah, if you treat `flat` as a prop then it's indeed out-of-scope of UnoCSS. But if underneath you are still using CSS, I am imagining something like:

```ts
rule: [
  [/^flat$/, () => `
.q-btn.flat {
  /* flat button */
}
.q-card.flat {
  /* flat card */
}
`
]
```

but that's just an idea anyway, use what make more sense to you :)

**Comment by ldiebold** [comment]
Will do some more digging. if quasar's design classes like `flat` are only changing css, this is a non-issue.
need to do my research :sweat_smile:

**Comment by antfu** [comment]
Closing as this is more related to the Quasar side. Please keep track there.
