### ISSUE TITLE
Is able to support responsive breakpoint control `<md:$vars`?

### ISSUE THREAD

**Issue by liuqian1996** [antfu/unocss#261]
[Windicss Variants](https://windicss.org/utilities/variants.html#variants)
[Windicss responsive-design](https://windicss.org/features/#responsive-design)

<img width="814" alt="image" src="https://user-images.githubusercontent.com/11707934/145707609-155e385a-e094-4eee-992e-e083e405ad19.png">

**Comment by userquin** [comment]
we don't use those symbols, see https://github.com/antfu/unocss/issues/181#issuecomment-982443908

**Comment by liuqian1996** [comment]
> we don't use those symbols, see [#181 (comment)](https://github.com/antfu/unocss/issues/181#issuecomment-982443908)

Thank you, but have a question, if nedd a breakpoint control, it must be set `sm` and `lt-sm` ?

eg: `p-1 lt-sm:p-8` whatever how moved their position, `lt-sm:p-8` always output before `p-1`, so `p-1` must add a `sm`? 

<img width="885" alt="image" src="https://user-images.githubusercontent.com/11707934/145709056-4238fbc8-e138-4f48-bb39-211b978693e4.png">

**Comment by userquin** [comment]
you should use `sm:p1`  or `sm:p-1`

**Comment by liuqian1996** [comment]
> you should use `sm:p1` or `sm:p-1`

can't set a default value?

**Comment by userquin** [comment]
@liuqian1996  I'm reviewing the order

**Comment by userquin** [comment]
@liuqian1996 I think I have fiex it on local, the problem is on the order the bp variants are included. We use the size as the order and when  using `lt-` we use the negative value and so that variants go to first styles. Instead using the order, I use a fixed order, for example 1000, and then add or substract the index  of the breakpoints.

This way we'll have always the breakpoint variants to be the lasts ones on the css output.

**Comment by liuqian1996** [comment]
@userquin Thank you for spent your time to fixed this issue

**Comment by userquin** [comment]
@liuqian1996 fixed on new version just released `0.16.2`

**Comment by liuqian1996** [comment]
@userquin It works, thank you
