### ISSUE TITLE
Svelte-scoped mode does not take into consideration that a component already has a style tag

### ISSUE THREAD

**Issue by MathiasWP** [antfu/unocss#447]
Svelte only accepts 1 style tag per component, so this behaviour forces the user to not use any style tags in their component.

Source: https://github.com/antfu/unocss/commit/0617733e8075ccc8953527c6a26409a600e3c3bf#diff-ac394d603804c8ed219c43572638b9f66088f440025a822da4e9fa4bdb4ae5cb

**Comment by vipero07** [comment]
This is a copy of vue-scoped (which is in beta), the expectation (at least mine are) users are only using atomic css. However this can easily be amended, I'll push an update to handle that case.

**Comment by vipero07** [comment]
https://github.com/vipero07/unocss/tree/fix(svelte-scoped)--append-css-to-existing-styles

Here is a fix, but I don't want to push it without some more thorough review. As it is merely searching for </style> and appending the new styles inside. This could have unforeseen consequences like the use of that tag inside a text string in the svelte file. Honestly though the whole point of using scoped css in svelte with an atomic css processor seems redundant to also have style tags.

My personal preference is to force the user to not use style tags in their component (since it is counter atomic css usage anyhow) and maybe just document that. It is easy enough to add rules shortcuts and variants.

**Comment by antfu** [comment]
Vue supports multiple style tags in SFC so it's nonproblem in Vue. If Svtele only allows one, we could merge it when there is already one presented. PR welcome
