### ISSUE TITLE
Inspector not accessible

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [antfu/unocss#476]
I have Vitesse Lite here: https://localhost:3001/gateway/

I'm unable to access the inspector: http://localhost:3000/__unocss

Please is there any setup or config needed? [vite.config.ts.txt](https://github.com/antfu/unocss/files/7868471/vite.config.ts.txt)

**Comment by CharlesOkwuagwu** [comment]
ok so I restarted the dev server on 3000 and it now works: https://localhost:3000/__unocss#/

Please can we adjust Inspector to run under the current port?

**Comment by userquin** [comment]
@CharlesOkwuagwu we have the PR #408 to fix a few things about server, we need to do a final review and should fix also fix this (use `Vite` base and port).

**Comment by userquin** [comment]
upps, sorry @CharlesOkwuagwu this is not related to #408, it should be fixed partially with #368, we need to review the port.

**Comment by CharlesOkwuagwu** [comment]
> upps, sorry @CharlesOkwuagwu this is not related to #408, it should be fixed partially with #368, we need to review the port.

Okay

**Comment by userquin** [comment]
you have the port `3000` in use,  `vite` will start dev server in the next port available and so you cannot access to port 3000 because of this: your vite config has not `server: { port: 3001 }`, just try adding it and should work (tested on local)

![imagen](https://user-images.githubusercontent.com/6311119/149522991-98e11534-d0d1-4e61-aad0-dd64bcd55066.png)
