### ISSUE TITLE
grid grid-rows-[auto,1fr,auto]     no effect

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#492]
grid grid-rows-[auto,1fr,auto]     no effect，
1、https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwHIDmAnMIo54C02A9gO5JEDaCArgC6kA0AjAGbbP1MC66APihQAUMOAALAKYIQU7FABGpbHOwZWg6bPnAA9NrUCxUYAFsEYAHZKVajYIvX9Tq8fHtSpBvNur5DgKe3rp6wT7YxvrgEAJAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHE6kAlEA&options=N4IgzgLgTglgxhEAuaBXApgXyA

2、dev
![image](https://user-images.githubusercontent.com/20468762/149649033-0c153f6f-0ece-4aff-8da0-d216344b306d.png)

**Comment by wheatjs** [comment]
The new syntax is `_` instead of `,`. So use `grid-rows-[auto_1fr_auto]`, also see [this playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnMIoC2YAdgLQAWpAjAAw0TlQBGmp2ApiKQKx1Q542AewDuSUgG0EAVwAuQgPpUAZtgUz5AXXQA%2BAFBQooSDoCSs9gShVgAenAR9h44-OWoAJjsOnRn26sAZm8TPRDHIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g)

**Comment by 729902288** [comment]
@wheatjs ，先谢谢您， 再请问一下，这个新语法，是**哪里**可以系统的查看？

**Comment by wheatjs** [comment]
There is not official documentation for this yet I don't think. You can see the relevant PR here though https://github.com/antfu/unocss/pull/325
