### ISSUE TITLE
QUESTION: perf of icon

### ISSUE THREAD

**Issue by edwardnyc** [antfu/unocss#52]
Using mask attributes will affect performance, especially on mobile WebView. This is obvious when the number is large.

So this scheme is not suitable for TOC business?

**Comment by userquin** [comment]
Do you mean chrome browser or native webview app?

**Comment by edwardnyc** [comment]
> Do you mean chrome browser or native webview app?

OK, let me talk about the background first. I'm a developer of Chinese Internet companies. As users, we need to pay attention to the user experience when we do large-scale activities. According to past experience, CSS mask attribute may cause jamming on a small number of devices. (Focus on WebView app)

**Comment by userquin** [comment]
I'm also a webview developer, focused on android: do you know you can hint the app/view to use hardware acceleration (at least on android)? 

```xml
// Manifest.xml
    ...
    <application
        android:hardwareAccelerated="true"
    ...
        <activity android:name=".WebViewActivity"
            android:hardwareAccelerated="true"
 
```

I will try to make an android app using unocss with a large number of icons to do some testing...

Maybe for some devices a lot of icons will affect perfomance since it depends on the hardware on the device...

For that devices, I think some tx/anim will also affect perfomance since these tx/anim should be handle by the GPU.

I have developed a lot of private apps with Polymer 1.5 (webcomponent 1.0) with hundred of pages (the app navigates local web app from apk assets): testing the apps on a Samsung Galaxy Tab A2 (Android 5/2015) or Lenovo Tab 7 Essential (Android 7/2016) have perfomance impact  on page  transition (fade in/out). The same apps running on Samsung Galaxy Note 10+ (Android 10) or Beista Tab 10" (Android 9), the page transition is fluid.

**Comment by userquin** [comment]
Maybe we can include a variant to force to use the icon as bg image (loosing colors when `currentColor` inside), something similar to `@media (prefers-reduced-motion: reduce)` using some global `un-prefer-bgimage-icon` css var (the responsability will be for the client to add it).

**Comment by edwardnyc** [comment]
What you said is very reasonable, but as developers, we need to be responsible for the product results. In many scenarios, there are Lottie, SVGA, transparent video, a large number of 3D animation and so on. Attributes such as mask or filter are considered disabled by us.
@userquin

**Comment by edwardnyc** [comment]
It's hard to describe. For example, in order to be compatible with Android 4.4, our new project still needs to use vue2 instead of vue3.

**Comment by userquin** [comment]
@edwardnyc then we need to find a way to force icons to use bg-image instead mask

**Comment by userquin** [comment]
So we can have this general style, now we need to add some rule:
```css
.prefer-bgimage-icon {
    mask: none !important;
    -webkit-mask: none !important;
    background-color: transparent !important;
    background: var(--un-icon) no-repeat;
    background-size: 100% 100%;
}
```

we only need to find a way to enable it.

**Comment by userquin** [comment]
@edwardnyc https://imgur.com/onEoV63

**Comment by userquin** [comment]
@edwardnyc here the exmaple: here the example https://github.com/userquin/unocss-prefer-bgimage-icons

**Comment by userquin** [comment]
I will test on android webview app: I'll add also the repo for the android app (latest android studio with kotlin + jetpack compose).

About the previous repo, I was thinking using some `html.prefer-bgimage-icon` and so we also need to add some class to icons instead since we haven't a way to do a css selecctor for elements with some attribute starting with `i-`.

@antfu maybe you can help here with some suggestion: the idea is to use previous css class or similar on top of `html` or maybe on the app root html element, and so, we can enable `prefer-bg-image-icons` to override existing ones with bg image instead using mask.

**Comment by edwardnyc** [comment]
Hard work, excellent. However, the effect you provide is actually on the PC, and the scene is simple enough. It's no problem just to render the mask itself @userquin

**Comment by edwardnyc** [comment]
I will look for relevant information to quantify the impact

**Comment by antfu** [comment]
> iit is only for testing purposes, the flag is initially enabled and so all icons will be using bg-image, and so you we can test on device directly.
> 
> You can clone the repo and just change `vue3` with `vue2` and do some testing on android 4.4.

There is a mode option in the icons preset

**Comment by userquin** [comment]
@antfu but then we need 2 builds, and this is not what I want

@edwardnyc updated repo to use class instead attributes on icons, and so we can have a css selector for it

**Comment by userquin** [comment]
EDIT: the codebase on android app is the native app with the webapp build, that will be shipped inside de android app, that is inside the APK file.

**Comment by userquin** [comment]
On android device we can do this:
```kotlin
// webview
class XWebView: WebView {
   constructor(context: Context) : super(context) {
        settings.apply {
            javaScriptEnabled = true
            allowFileAccess = false
            builtInZoomControls = true
            displayZoomControls = false
        }
        addJavascriptInterface(XCapiApp(), "XCapiApp")
        ...
   }
}
// XCapiApp
class XCapiApp {
    @JavascriptInterface
    fun preferBgImageIcons(): Boolean {
     return <some boolean with logic>
}
```

then on the webapp repo we will have something like this:
```vue
<script setup lang="ts">
import { ref } from 'vue'
const checked = ref(typeof window.XCapi !== 'undefined' ? window.XCapi.preferBgImageIcons(): false)
</script>
```

**Comment by userquin** [comment]
Running app on android emulator, I need to fix the width for mobile (I will also push the repo later with instructions):

https://imgur.com/CsYDcQ7

**Comment by userquin** [comment]
@antfu you can see here how we can use the `window.XCapiApp.preferBgImageIcons()` function

https://imgur.com/W6fDMpt

**Comment by userquin** [comment]
@edwardnyc https://github.com/userquin/droid-unocss-prefer-bgimage-icons
