### ISSUE TITLE
Strategy to implement forms plugin

### ISSUE THREAD

**Issue by sibbng** [antfu/unocss#54]
I tried implementing forms plugin, but it's not straight forward as it be in Tailwind.

First of all, how forms plugin work _([@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) in this case)_:

- Has two strategies:
  - Attribute, element, pseudo element selectors: `[type='checkbox']`, `select`, `::-webkit-datetime-edit-fields-wrapper` etc.
  - Class selectors: `.form-checkbox`, `.form-select`
- Styles are always present in output, not generated on-demand
- Don't need to work with variants
- They need to be defined before utilities, so we can override form styles

### Why can't use current APIs?

First of all, they are all oriented on generating styles on-demand based on classnames.

#### [Full Controlled Rules](https://github.com/antfu/unocss#full-controlled-rules)
- This way requires a class to activate styles. This would work if we were only using class mode (`.form-input` etc), and we still need pseudo element selectors in global scope.

#### Mixing with attributify mode
- Defining rules like `type-checkbox`, `type-radio` will match input elements with `type="checkbox"` attribute. Still generated on-demand and can have side effects since it also supports `.type-checkbox` class.

Generating these styles on-demand is not bad, but not having an option to always generate them is bad. Because whitelisting multiple selectors like `[type='checkbox']` or `.form-checkbox` is quite painful.

### Solutions:
- An API to push pure CSS styles on top of generated output. This would also made possible generating reset styles in presetUno with an option like `preflight: true`
- Since forms plugin have no dynamic rules and don't need to work variants, we can simply provide 2 css files with attribute and class selectors and let users to import them in their entry point like how they do for reset styles. _(Preferred in short term)_
- `addBase` like API _(Strongly preferred in long term)_:
  - Extract and generate attribute, element and id selectors on-demand
  - An option to forcefully generate static selectors: `[type='checkbox']`, `select`
  - Always generate unextractable selectors: `::-webkit-datetime-edit-fields-wrapper`

Second solution is possible today, but I prefer first two solutions combined. But in the long term third way sounds better.

**Comment by antfu** [comment]
I would actually feel the forms plugin is a bit over-engineering - it's more like they want it as a plugin for the eco but not the thing that really needs to be a plugin.

Since it doesn't expect either on-demand or variants - I would think it's actually better to be served as plain CSS. For example:

```js
import 'my-forms-plugin/attribute.css' // or 'class.css' for class strategies
import 'uno.css'
```

I guess unocss could provide an API to inject raw CSS in the generated CSS in the future, but for this case, I think importing the plain CSS is pretty enough. (for the class strategies, I guess it's straightforward to implement in UnoCSS with the on-demand capability)

**Comment by sibbng** [comment]
I agree about your over-engineering comment. 

Should we provide this css files under unocss. Like `@unocss/forms/attribute.css` and `@unocss/forms/class.css`? I'm also thinking about implementing single dynamic rule that makes possible changing color of radio and checkbox icons.

**Comment by antfu** [comment]
I am working on the layers support #56 and later will provide an API for "preflights". So that we could have a similar thing as a preset and based on the strategies, we could provide raw CSS for `attribute` mode, and smarter on-demand classes for `class` mode.

> implementing single dynamic rule that makes possible changing color of radio and checkbox icons.

That sounds cool. Would you expect it to work only on class mode or also the attribute mode?

**Comment by sibbng** [comment]
It works with both modes. It just works like how preset-icons do: using mask. I will move icon to `::after` pseudo element and create an color utility that adds `color` property that.

**Comment by jd-0001** [comment]
Is the forms plugin/preset available or still in development?
